"""STM32 (HAL / CubeIDE) firmware discoverer.

Finds the canonical entry points exposed by an STM32CubeIDE / STM32CubeMX
project (`STM32*.ld` + `Core/Src/main.c` + `Core/Src/stm32f*xx_it.c`):

- `int main(void)` → MAIN_FUNCTION — the STM32 firmware boot entry.
- `<Foo>_IRQHandler(void)` → ISR_VECTOR — every IRQ handler whose name
  ends in `_IRQHandler` is a vector-table entry generated by CubeMX.
  `<Foo>` (e.g. `EXTI0`, `TIM2`, `USART2`) is kept on `metadata.irq`.
- `HAL_<Module>_<Event>Callback(<args>)` → EVENT_LISTENER — every weak
  HAL callback override the user has implemented (UART RX done, ADC
  conversion complete, GPIO EXTI, etc.). The full module + event split
  is kept on `metadata.{hal_module, hal_event}`.

`type_origin` is hard-coded to `"firmware_stm32"`. The walker is
type-blind and reads only the EntryPoint schema fields; type knowledge
is crystallised into the metadata dict.

Heuristic, not AST-perfect, but deterministic. Output is sorted by
`(file, line, symbol, kind)` — required for byte-identical goldens.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..types import EntryPoint, EntryPointKind

# int main(void) — column-zero, void-arg. STM32 firmware always uses the
# `int main(void)` signature (CubeMX never generates `int main(int, char**)`).
_MAIN_RE = re.compile(r"^\s*int\s+main\s*\(\s*void\s*\)\s*\{", re.MULTILINE)

# <Foo>_IRQHandler(void) at column 0. Whitespace before `void` and
# alignment-mode return types is tolerated; we look for the canonical
# CubeMX-generated form. The captured `<Foo>` is the IRQ vector name.
_IRQ_HANDLER_RE = re.compile(
    r"^\s*void\s+(?P<irq>[A-Za-z_][A-Za-z0-9_]*)_IRQHandler\s*\(\s*void\s*\)\s*\{",
    re.MULTILINE,
)

# HAL_<Module>_<Event>Callback(...) — the weak HAL callback override
# convention. CubeMX-generated callbacks all follow this pattern. We
# capture the module + event split for metadata; the full symbol is
# reconstructed for `symbol`.
_HAL_CALLBACK_RE = re.compile(
    r"^\s*(?:void|HAL_StatusTypeDef)\s+"
    r"HAL_(?P<module>[A-Za-z][A-Za-z0-9]*)_"
    r"(?P<event>[A-Za-z][A-Za-z0-9]*?)Callback\s*\(",
    re.MULTILINE,
)


_SKIP_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        "node_modules",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".cache",
        ".idea",
        ".vscode",
        "build",
        "dist",
        "out",
        "bin",
        "obj",
        # CubeIDE keeps build artefacts under Debug/Release per-configuration.
        "Debug",
        "Release",
        # Drivers/Middlewares come pre-shipped with CubeMX — they aren't
        # the user's code so they don't contribute application-level
        # entry points. (The HAL callback `weak` defaults live there and
        # would otherwise be picked up as bogus entries.)
        "Drivers",
        "Middlewares",
        "Utilities",
        # Tests / fixtures bundled in nested example apps.
        "tests",
        "test",
        "samples",
        "sample",
        "examples",
        "example",
        "doc",
        "docs",
        "tests_dev",
        "reports",
        "reports_dev",
        "docs_dev",
        "scripts_dev",
        "samples_dev",
        "examples_dev",
    }
)


CONTENT_PREVIEW_BYTES = 262144  # 256 KiB — stm32f*xx_it.c can be larger than 128 KiB


def _read(path: Path) -> str:
    """Read up to CONTENT_PREVIEW_BYTES of `path`. Empty string on OSError."""
    try:
        return path.read_bytes()[:CONTENT_PREVIEW_BYTES].decode("utf-8", errors="replace")
    except OSError:
        return ""


def _line_of(text: str, offset: int) -> int:
    """1-indexed line number of `offset` within `text`."""
    return text.count("\n", 0, offset) + 1


def _iter_c_files(repo_root: Path) -> list[Path]:
    """Sorted list of *.c files under `repo_root`, with skip-dirs filtered.

    Skip-dir filtering uses path components RELATIVE to `repo_root`.
    """
    out: list[Path] = []
    for p in repo_root.rglob("*.c"):
        if not p.is_file():
            continue
        try:
            rel_parts = p.relative_to(repo_root).parts
        except ValueError:
            continue
        if any(part in _SKIP_DIRS for part in rel_parts[:-1]):
            continue
        out.append(p)
    out.sort()
    return out


def discover(repo_root: Path, languages: list[str]) -> list[EntryPoint]:
    """Find STM32 entry points. Deterministic order.

    `languages` is the language list emitted by the language detector.
    We require `"c"` to be present.
    """
    if "c" not in languages:
        return []

    repo_root = repo_root.resolve()
    found: list[EntryPoint] = []

    for path in _iter_c_files(repo_root):
        text = _read(path)
        if not text:
            continue
        rel = str(path.relative_to(repo_root))

        # ---- int main(void) → MAIN_FUNCTION -------------------------------
        for m in _MAIN_RE.finditer(text):
            line = _line_of(text, m.start())
            found.append(
                EntryPoint(
                    kind=EntryPointKind.MAIN_FUNCTION,
                    file=rel,
                    line=line,
                    symbol="main",
                    type_origin="firmware_stm32",
                    metadata={"role": "stm32_main"},
                )
            )

        # ---- *_IRQHandler → ISR_VECTOR ------------------------------------
        for m in _IRQ_HANDLER_RE.finditer(text):
            irq = m.group("irq")
            symbol = f"{irq}_IRQHandler"
            line = _line_of(text, m.start())
            found.append(
                EntryPoint(
                    kind=EntryPointKind.ISR_VECTOR,
                    file=rel,
                    line=line,
                    symbol=symbol,
                    type_origin="firmware_stm32",
                    metadata={"irq": irq},
                )
            )

        # ---- HAL_<Module>_<Event>Callback → EVENT_LISTENER ----------------
        for m in _HAL_CALLBACK_RE.finditer(text):
            module = m.group("module")
            event = m.group("event")
            symbol = f"HAL_{module}_{event}Callback"
            line = _line_of(text, m.start())
            found.append(
                EntryPoint(
                    kind=EntryPointKind.EVENT_LISTENER,
                    file=rel,
                    line=line,
                    symbol=symbol,
                    type_origin="firmware_stm32",
                    metadata={
                        "hal_module": module,
                        "hal_event": event,
                    },
                )
            )

    # Dedup by (file, line, symbol, kind) — same IRQ handler appearing
    # twice in the same file is a real bug, but the discoverer reports
    # one entry per source occurrence (not per declaration).
    seen: set[tuple[str, int, str, str]] = set()
    unique: list[EntryPoint] = []
    for ep in found:
        key = (ep.file, ep.line, ep.symbol, ep.kind.value)
        if key in seen:
            continue
        seen.add(key)
        unique.append(ep)

    unique.sort(key=lambda e: (e.sort_key(), e.kind.value))
    return unique
