#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# ///
"""Step 6 — Cross-layer drift detector (TRDD-7e364ace clusters E1-E10, Q1, Q5).

Deterministic scan for cross-layer drift — the kind of bug that hides
between layers (code vs. docs, ORM vs. migration, hand-written vs.
generated, modern call site vs. retired API). Three checks ship in
this script:

1. **Env-var drift** — every `os.environ.get(X)` / `os.getenv(X)` /
   `process.env.X` / `process.env["X"]` / `env::var("X")` / `ENV["X"]`
   reference in source is compared against every env declaration in
   `.env.example` / `.env.sample` / `.env.template` /
   `docker-compose.{yml,yaml}` / `compose.{yml,yaml}`. Bi-directional:
   `USED_IN_CODE` lists vars referenced in source but absent from every
   doc/config; `DOCUMENTED_BUT_UNUSED` lists vars declared in a
   .env-style file but never referenced from code.

2. **Generated-file edit detection** — files containing a `@generated`,
   `Code generated by`, or `DO NOT EDIT` banner in their first 50 lines.
   The downstream agent decides whether the edits are intentional
   re-generation runs or accidental drift; the script's job is to
   surface the candidate list.

3. **Orphan naming scan** — symbol references matching deprecated-name
   patterns (`_v1`, `_v2`, `_old`, `_new`, `_legacy`, `_deprecated`).
   These are weak signals — the agent confirms. Each hit names the
   file:line and the matched symbol slice.

Out of scope for the script (deferred to the existing
`caa-cross-layer-auditor-agent` agent for judgment):
- Schema/model drift (requires understanding ORM-vs-migration semantics)
- UI-only security gaps (requires reading server-side authz to be sure)
- Removed-state-no-replacement (requires reading the diff before/after)

Usage:
    python -m scripts.prereview.cross_layer <repo_root> <out_dir>
        [--pr-files-from <txt>]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from collections.abc import Iterable
from dataclasses import asdict, dataclass
from pathlib import Path

SCHEMA_VERSION = 1
SCAN_CAP_BYTES = 200_000  # cap per-file read so we never blow memory on huge generated files
GENERATED_BANNER_LINES = 50

# Skip every cache / build artifact / dev-scratch dir — same set the gate uses.
_SKIP_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        "node_modules",
        "__pycache__",
        ".venv",
        "venv",
        ".tox",
        ".mypy_cache",
        ".ruff_cache",
        ".pytest_cache",
        "dist",
        "build",
        "target",
        ".cache",
        ".idea",
        ".vscode",
        "reports",
        "reports_dev",
        "docs_dev",
        "scripts_dev",
        "tests_dev",
        "samples_dev",
        "examples_dev",
        "downloads_dev",
        "libs_dev",
        "builds_dev",
        ".trashcan",
        ".terraform",
        ".pulumi",
        ".gradle",
        ".cargo",
    }
)

# File extensions worth scanning for code references — leave out binaries,
# images, archives, hand-curated docs lists.
_CODE_EXTS: frozenset[str] = frozenset(
    {
        ".py",
        ".pyi",
        ".js",
        ".mjs",
        ".cjs",
        ".jsx",
        ".ts",
        ".tsx",
        ".mts",
        ".cts",
        ".go",
        ".rs",
        ".rb",
        ".swift",
        ".java",
        ".kt",
        ".kts",
        ".cs",
        ".ex",
        ".exs",
        ".sh",
        ".bash",
        ".zsh",
        ".php",
        ".c",
        ".cpp",
        ".h",
        ".hpp",
        ".m",
        ".mm",
    }
)

_ENV_DECL_FILES: frozenset[str] = frozenset(
    {
        ".env",
        ".env.example",
        ".env.sample",
        ".env.template",
        ".env.local",
        ".env.dist",
        ".env.development",
        ".env.production",
        ".env.test",
    }
)

# Patterns to extract env-var REFERENCES from source.
# Order matters: more specific first so a single match doesn't fire twice.
_ENV_REF_PATTERNS: tuple[tuple[re.Pattern[str], int], ...] = (
    # os.environ.get("X") / os.environ.get('X') / os.getenv("X")
    (re.compile(r"""os\.environ\.get\(\s*['"]([A-Z_][A-Z0-9_]*)['"]"""), 1),
    (re.compile(r"""os\.getenv\(\s*['"]([A-Z_][A-Z0-9_]*)['"]"""), 1),
    # os.environ["X"]  or  os.environ['X']
    (re.compile(r"""os\.environ\[\s*['"]([A-Z_][A-Z0-9_]*)['"]\]"""), 1),
    # process.env.X  or  process.env["X"]
    (re.compile(r"""process\.env\.([A-Z_][A-Z0-9_]*)"""), 1),
    (re.compile(r"""process\.env\[\s*['"]([A-Z_][A-Z0-9_]*)['"]\]"""), 1),
    # Rust: std::env::var("X") or env::var("X")
    (re.compile(r"""env::var\(\s*['"]([A-Z_][A-Z0-9_]*)['"]"""), 1),
    # Go: os.Getenv("X")
    (re.compile(r"""os\.Getenv\(\s*['"]([A-Z_][A-Z0-9_]*)['"]"""), 1),
    # Ruby/Crystal: ENV["X"]
    (re.compile(r"""\bENV\[\s*['"]([A-Z_][A-Z0-9_]*)['"]\]"""), 1),
    # Bash: ${X} or $X for ALL-CAPS — narrow to plausible env-style vars
    # only (must be ALL_CAPS_WITH_UNDERSCORE; >=2 chars).
    (re.compile(r"""\$\{?([A-Z][A-Z0-9_]{1,})\}?\b"""), 1),
)

# Variants of the "do not hand-edit" banner used by code generators.
_GENERATED_BANNERS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p)
    for p in (
        r"@generated\b",
        r"Code generated by",
        r"^// DO NOT EDIT\b",
        r"^# DO NOT EDIT\b",
        r"<!-- DO NOT EDIT -->",
        r"/\*\s*\*\s*AUTOGENERATED FILE\s*\*",
        r"\bautogenerated\b",
        r"This file is automatically generated",
    )
)

# Identifier-suffix patterns that often mark deprecated / dual-version code.
_ORPHAN_SUFFIX_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]{1,}(?:_v\d+|_old|_new|_legacy|_deprecated|_v2))\b")


@dataclass(frozen=True, slots=True)
class Finding:
    """Normalised output for any cross-layer check."""

    tool: str
    category: str
    file: str
    line: int
    severity: str
    code: str
    message: str


# ---- File enumeration ------------------------------------------------------


def _enumerate_repo(repo_root: Path) -> list[Path]:
    """Walk `repo_root` honouring `_SKIP_DIRS`, return absolute paths sorted."""
    out: list[Path] = []
    import os

    for dirpath, dirnames, filenames in os.walk(repo_root):
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        for fname in sorted(filenames):
            out.append(Path(dirpath) / fname)
    return out


def _load_pr_files(repo_root: Path, path: Path | None) -> list[Path] | None:
    if path is None:
        return None
    if not path.is_file():
        raise FileNotFoundError(f"--pr-files-from: not found: {path}")
    files: list[Path] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        rel = line.strip()
        if not rel or rel.startswith("#"):
            continue
        abs_path = (repo_root / rel).resolve()
        # Confine to the repo tree: a `../../etc/hosts` listing entry resolves
        # outside repo_root (out-of-tree read). Mirrors concurrency.py's fix.
        if abs_path.is_file() and abs_path.is_relative_to(repo_root.resolve()):
            files.append(abs_path)
    return sorted(set(files))


def _read_text_capped(path: Path, cap: int = SCAN_CAP_BYTES) -> str:
    try:
        with path.open("rb") as f:
            data = f.read(cap)
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _rel(repo_root: Path, path: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.name


# ---- Env-var drift ---------------------------------------------------------


def _scan_env_references(repo_root: Path, files: Iterable[Path]) -> dict[str, list[tuple[str, int]]]:
    """Return {VAR_NAME: [(file, line), ...]} for every env-var reference.

    Bash `$VAR` matches are inherently noisy (any all-caps token after `$`
    could be a local var). We accept the noise; the agent can dedup
    against declared vars later. The dedup pass downstream uses set
    membership against documented vars, so noise → false-NEGATIVE risk
    in the drift report, not false-positive.
    """
    references: dict[str, list[tuple[str, int]]] = {}
    for path in files:
        if path.suffix.lower() not in _CODE_EXTS:
            continue
        text = _read_text_capped(path)
        if not text:
            continue
        rel = _rel(repo_root, path)
        for line_idx, line in enumerate(text.splitlines(), start=1):
            seen_on_line: set[str] = set()
            for pat, group in _ENV_REF_PATTERNS:
                for m in pat.finditer(line):
                    name = m.group(group)
                    # Skip lowercase/short matches that don't look like env vars.
                    if not _looks_like_env_name(name):
                        continue
                    if name in seen_on_line:
                        continue
                    seen_on_line.add(name)
                    references.setdefault(name, []).append((rel, line_idx))
    return references


def _looks_like_env_name(name: str) -> bool:
    """Filter for plausible env-var names.

    Heuristic: at least 2 chars, all caps + digits + underscores, must
    contain an underscore OR be at least 4 chars. This filters out
    single-letter shell variables like `$X` while keeping `$PORT`,
    `$DATABASE_URL`, etc.
    """
    if len(name) < 2:
        return False
    if not name.isupper():
        return False
    if "_" in name:
        return True
    return len(name) >= 4


def _scan_env_declarations(repo_root: Path, files: Iterable[Path]) -> dict[str, list[tuple[str, int]]]:
    """Parse .env-style files for declared variable names."""
    decls: dict[str, list[tuple[str, int]]] = {}
    for path in files:
        if path.name not in _ENV_DECL_FILES and not _is_compose_file(path):
            continue
        text = _read_text_capped(path)
        if not text:
            continue
        rel = _rel(repo_root, path)
        if _is_compose_file(path):
            for var, line in _iter_compose_env(text):
                decls.setdefault(var, []).append((rel, line))
        else:
            for var, line in _iter_dotenv(text):
                decls.setdefault(var, []).append((rel, line))
    return decls


def _is_compose_file(path: Path) -> bool:
    return path.name in {"docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"}


def _iter_dotenv(text: str) -> Iterable[tuple[str, int]]:
    """Yield (var_name, line_no) for each KEY=value line."""
    for line_idx, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Strip `export ` prefix (some .env files include it).
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key = line.split("=", 1)[0].strip()
        if _looks_like_env_name(key):
            yield key, line_idx


def _iter_compose_env(text: str) -> Iterable[tuple[str, int]]:
    """Yield (var_name, line_no) for entries under any `environment:` block.

    Lightweight parser — assumes the indented YAML form is either
    `- KEY=val` or `- KEY=${KEY}` or `KEY: val`. Anything more exotic
    (anchors, merge keys, nested maps) is left to the LLM to confirm.
    """
    in_env_block = False
    env_block_indent = -1
    for line_idx, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.lstrip()
        indent = len(raw) - len(stripped)
        if stripped.startswith("environment:"):
            in_env_block = True
            env_block_indent = indent
            continue
        if in_env_block and indent <= env_block_indent and stripped:
            in_env_block = False
        if not in_env_block:
            continue
        line = stripped.strip()
        if line.startswith("- "):
            line = line[2:]
        key = line.split("=", 1)[0].split(":", 1)[0].strip()
        if _looks_like_env_name(key):
            yield key, line_idx


def _find_env_var_drift(
    refs: dict[str, list[tuple[str, int]]],
    decls: dict[str, list[tuple[str, int]]],
    pr_mode: bool = False,
) -> list[Finding]:
    """Compute bi-directional drift findings."""
    out: list[Finding] = []
    declared = set(decls.keys())
    referenced = set(refs.keys())
    for var in sorted(referenced - declared):
        # First reference for compact report.
        first_file, first_line = refs[var][0]
        out.append(
            Finding(
                tool="cross_layer",
                category="env_var_drift",
                file=first_file,
                line=first_line,
                severity="warning",
                code="USED_IN_CODE_NOT_DOCUMENTED",
                message=f"Env var '{var}' referenced in code but not declared in any .env* / compose env block",
            )
        )
    # DOCUMENTED_NOT_USED is unreliable in PR mode: declarations are scanned
    # repo-wide but references come ONLY from the PR-touched subset, so
    # `declared - referenced` would flag every documented env var the PR didn't
    # touch (a false-positive bomb). Only emit it in whole-repo mode.
    if not pr_mode:
        for var in sorted(declared - referenced):
            first_file, first_line = decls[var][0]
            out.append(
                Finding(
                    tool="cross_layer",
                    category="env_var_drift",
                    file=first_file,
                    line=first_line,
                    severity="nit",
                    code="DOCUMENTED_NOT_USED",
                    message=f"Env var '{var}' declared in {first_file} but never referenced from code",
                )
            )
    return out


# ---- Generated-file edit candidates ----------------------------------------


def _find_generated_files(repo_root: Path, files: Iterable[Path]) -> list[Finding]:
    out: list[Finding] = []
    for path in files:
        # We scan ANY non-binary file; codegens emit *.go/*.ts/*.py/*.proto etc.
        if path.suffix.lower() not in _CODE_EXTS and path.suffix.lower() not in {
            ".md",
            ".json",
            ".yaml",
            ".yml",
            ".proto",
            ".graphql",
            ".gql",
        }:
            continue
        text = _read_text_capped(path)
        if not text:
            continue
        # Inspect only the first N lines — banners are at the top.
        head = "\n".join(text.splitlines()[:GENERATED_BANNER_LINES])
        for pat in _GENERATED_BANNERS:
            m = pat.search(head)
            if not m:
                continue
            out.append(
                Finding(
                    tool="cross_layer",
                    category="generated_drift",
                    file=_rel(repo_root, path),
                    line=1,
                    severity="info",
                    code="GENERATED_BANNER_PRESENT",
                    message=f"File carries a generated marker ({m.group(0)!r}); verify it wasn't hand-edited",
                )
            )
            break
    return out


# ---- Orphan-naming scan ----------------------------------------------------


def _find_orphan_names(repo_root: Path, files: Iterable[Path]) -> list[Finding]:
    out: list[Finding] = []
    for path in files:
        if path.suffix.lower() not in _CODE_EXTS:
            continue
        text = _read_text_capped(path)
        if not text:
            continue
        rel = _rel(repo_root, path)
        per_line_seen: set[tuple[int, str]] = set()
        for line_idx, line in enumerate(text.splitlines(), start=1):
            for m in _ORPHAN_SUFFIX_RE.finditer(line):
                name = m.group(1)
                key = (line_idx, name)
                if key in per_line_seen:
                    continue
                per_line_seen.add(key)
                out.append(
                    Finding(
                        tool="cross_layer",
                        category="orphan_naming",
                        file=rel,
                        line=line_idx,
                        severity="nit",
                        code="DEPRECATED_NAME_SUFFIX",
                        message=f"Symbol '{name}' uses a deprecated-name suffix",
                    )
                )
    return out


# ---- Driver ---------------------------------------------------------------


def _local_timestamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S%z", time.localtime())


def detect(repo_root: Path, pr_files: list[Path] | None = None) -> dict[str, object]:
    if not repo_root.is_dir():
        raise NotADirectoryError(f"repo_root is not a directory: {repo_root}")
    all_files = pr_files if pr_files is not None else _enumerate_repo(repo_root)
    # Env var pass needs the .env* / compose files even if not in the
    # PR-touched subset — drift between PR-changed code and unchanged docs
    # is exactly the bug we want to catch. So when PR-files-from is set,
    # we still scan the WHOLE repo for declarations; references come from
    # the PR subset (since referenced-but-not-documented is bug-relevant
    # only for new/changed code).
    if pr_files is not None:
        all_repo_files = _enumerate_repo(repo_root)
        decl_files = all_repo_files
    else:
        decl_files = all_files
    refs = _scan_env_references(repo_root, all_files)
    decls = _scan_env_declarations(repo_root, decl_files)
    env_drift = _find_env_var_drift(refs, decls, pr_mode=pr_files is not None)
    generated = _find_generated_files(repo_root, all_files)
    orphans = _find_orphan_names(repo_root, all_files)
    findings: list[Finding] = sorted(
        [*env_drift, *generated, *orphans],
        key=lambda f: (f.category, f.file, f.line, f.code),
    )
    # Counts by category for the downstream agent's at-a-glance.
    by_category: dict[str, int] = {}
    for f in findings:
        by_category[f.category] = by_category.get(f.category, 0) + 1
    return {
        "schema_version": SCHEMA_VERSION,
        "timestamp": _local_timestamp(),
        "repo_root": str(repo_root.resolve()),
        "total_findings": len(findings),
        "by_category": dict(sorted(by_category.items())),
        "findings": [asdict(f) for f in findings],
    }


def _parse_argv(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Step 6 — cross-layer drift detector.",
        prog="cross_layer",
    )
    parser.add_argument("repo_root", help="Absolute path to the repository to scan.")
    parser.add_argument("out_dir", help="Where the JSON report is written.")
    parser.add_argument(
        "--pr-files-from",
        help="Optional file: each line is a repo-relative path of a PR-touched file.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = _parse_argv(argv[1:])
    repo_root = Path(args.repo_root).resolve()
    out_dir = Path(args.out_dir).resolve()
    try:
        out_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"out_dir unwritable: {exc}", file=sys.stderr)
        return 1
    try:
        pr_files = _load_pr_files(repo_root, Path(args.pr_files_from) if args.pr_files_from else None)
        payload = detect(repo_root, pr_files)
    except (FileNotFoundError, NotADirectoryError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    out_path = out_dir / f"{payload['timestamp']}-cross_layer.json"
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
