#!/usr/bin/env python3
# /// script
# requires-python = ">=3.12"
# ///
"""Step 19 — Operational / deployment scanner (TRDD-7e364ace Q3-Q8).

Surface deployment / rollout hazards a deterministic pass can catch:

- `SCHEMA_NO_CODEGEN` — a schema source file (`.proto`, `.graphql`,
  `.gql`, `*.openapi.yaml`, `*.openapi.json`, `schema.json`, `*.tsp`)
  was touched by the PR, but NO file marked `@generated` /
  `Code generated by` / `DO NOT EDIT` was touched alongside. The
  codegen step probably wasn't re-run.
- `CI_NO_NOTES` — `.github/workflows/*.yml` / `.gitlab-ci.yml` /
  `*.yml` under `.circleci/` was touched, but no top-level
  `README.md` / `CHANGELOG.md` / `docs/` change was made in the same
  diff. Workflow drift without notes confuses future maintainers.
- `DOCKERFILE_NO_NOTES` — `Dockerfile` / `Containerfile` /
  `docker-compose*.yml` touched without a corresponding `README` /
  `docs/` change. Container changes without docs leave operators
  guessing.

The script accepts the unified diff path; the `--pr-files-from` form
is the canonical input from the orchestrator (one repo-relative path
per line).

Usage:
    python -m scripts.prereview.operational <repo_root> <out_dir>
        [--pr-files-from <txt>]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

SCHEMA_VERSION = 1
SCAN_CAP_BYTES = 200_000
GENERATED_BANNER_LINES = 50

_SKIP_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        "node_modules",
        "__pycache__",
        ".venv",
        "venv",
        ".tox",
        ".mypy_cache",
        ".ruff_cache",
        ".pytest_cache",
        "dist",
        "build",
        "target",
        ".cache",
        ".idea",
        ".vscode",
        "reports",
        "reports_dev",
        "docs_dev",
        "scripts_dev",
        "tests_dev",
        "samples_dev",
        "examples_dev",
        "downloads_dev",
        "libs_dev",
        "builds_dev",
        ".trashcan",
    }
)

_GENERATED_BANNERS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p)
    for p in (
        r"@generated\b",
        r"Code generated by",
        r"^// DO NOT EDIT\b",
        r"^# DO NOT EDIT\b",
        r"<!-- DO NOT EDIT -->",
        r"\bautogenerated\b",
        r"This file is automatically generated",
    )
)

_SCHEMA_NAME_RE = re.compile(
    r"(\.proto|\.graphql|\.gql|\.openapi\.ya?ml|\.openapi\.json|/schema\.json|\.tsp)$",
    re.IGNORECASE,
)

_CI_PATH_RE = re.compile(
    r"^(?:\.github/workflows/|\.gitlab-ci\.yml$|\.circleci/|azure-pipelines\.yml$|Jenkinsfile$)",
)

_DOCKER_NAME_RE = re.compile(
    r"(^|/)(Dockerfile(?:\.[\w\-.]+)?$|Containerfile$|docker-compose(?:\.[\w\-.]+)?\.ya?ml$|compose\.ya?ml$)",
    re.IGNORECASE,
)

_DOCS_NAME_RE = re.compile(
    r"(^|/)(README(?:\.md)?$|CHANGELOG(?:\.md)?$|docs/.+\.(md|rst|mdx)$|.*\.md$)",
    re.IGNORECASE,
)


@dataclass(frozen=True, slots=True)
class Finding:
    tool: str
    category: str
    file: str
    line: int
    severity: str
    code: str
    message: str


# ---- IO helpers ------------------------------------------------------------


def _enumerate_repo(repo_root: Path) -> list[Path]:
    out: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRS)
        for fname in sorted(filenames):
            out.append(Path(dirpath) / fname)
    return out


def _load_pr_files(repo_root: Path, path: Path | None) -> list[Path] | None:
    if path is None:
        return None
    if not path.is_file():
        raise FileNotFoundError(f"--pr-files-from: not found: {path}")
    files: list[Path] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        rel = line.strip()
        if not rel or rel.startswith("#"):
            continue
        abs_path = (repo_root / rel).resolve()
        if abs_path.is_file():
            files.append(abs_path)
    return sorted(set(files))


def _read_text_capped(path: Path) -> str:
    try:
        with path.open("rb") as f:
            data = f.read(SCAN_CAP_BYTES)
    except OSError:
        return ""
    return data.decode("utf-8", errors="ignore")


def _rel(repo_root: Path, path: Path) -> str:
    try:
        return path.relative_to(repo_root).as_posix()
    except ValueError:
        return path.name


# ---- Classifiers ----------------------------------------------------------


def _is_schema_source(rel: str) -> bool:
    return bool(_SCHEMA_NAME_RE.search(rel))


def _is_ci_path(rel: str) -> bool:
    return bool(_CI_PATH_RE.match(rel))


def _is_docker(rel: str) -> bool:
    return bool(_DOCKER_NAME_RE.search(rel))


def _is_docs(rel: str) -> bool:
    return bool(_DOCS_NAME_RE.search(rel))


def _is_generated_file(path: Path) -> bool:
    """File carries an `@generated` / `Code generated by` banner in its
    first N lines.
    """
    text = _read_text_capped(path)
    if not text:
        return False
    head = "\n".join(text.splitlines()[:GENERATED_BANNER_LINES])
    return any(pat.search(head) for pat in _GENERATED_BANNERS)


# ---- Checks ---------------------------------------------------------------


def _check_schema_codegen(repo_root: Path, files: list[Path]) -> list[Finding]:
    out: list[Finding] = []
    rels = [(_rel(repo_root, p), p) for p in files]
    schema_rels = [rel for rel, _ in rels if _is_schema_source(rel)]
    if not schema_rels:
        return out
    # Did the diff include at least one generated file?
    has_generated = any(_is_generated_file(p) for _, p in rels)
    if has_generated:
        return out
    for schema_rel in schema_rels:
        out.append(
            Finding(
                tool="operational",
                category="codegen_drift",
                file=schema_rel,
                line=1,
                severity="warning",
                code="SCHEMA_NO_CODEGEN",
                message=(
                    "schema source touched but no generated file (with @generated / "
                    "'Code generated by' banner) appears in the same diff — "
                    "did `make gen` / `npm run codegen` get skipped?"
                ),
            )
        )
    return out


def _check_ci_no_notes(repo_root: Path, files: list[Path]) -> list[Finding]:
    out: list[Finding] = []
    rels = [_rel(repo_root, p) for p in files]
    ci_rels = [rel for rel in rels if _is_ci_path(rel)]
    if not ci_rels:
        return out
    has_docs_touch = any(_is_docs(rel) for rel in rels)
    if has_docs_touch:
        return out
    for ci_rel in ci_rels:
        out.append(
            Finding(
                tool="operational",
                category="ci_no_notes",
                file=ci_rel,
                line=1,
                severity="nit",
                code="CI_NO_NOTES",
                message=(
                    "CI workflow touched but no README / CHANGELOG / docs change in the "
                    "same diff — future maintainers will not know why this changed"
                ),
            )
        )
    return out


def _check_docker_no_notes(repo_root: Path, files: list[Path]) -> list[Finding]:
    out: list[Finding] = []
    rels = [_rel(repo_root, p) for p in files]
    docker_rels = [rel for rel in rels if _is_docker(rel)]
    if not docker_rels:
        return out
    has_docs_touch = any(_is_docs(rel) for rel in rels)
    if has_docs_touch:
        return out
    for docker_rel in docker_rels:
        out.append(
            Finding(
                tool="operational",
                category="docker_no_notes",
                file=docker_rel,
                line=1,
                severity="nit",
                code="DOCKERFILE_NO_NOTES",
                message=(
                    "Dockerfile / compose file touched but no README / docs change — "
                    "operators will not know why this changed"
                ),
            )
        )
    return out


# ---- Driver ---------------------------------------------------------------


def _local_timestamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S%z", time.localtime())


def detect(repo_root: Path, pr_files: list[Path] | None = None) -> dict[str, object]:
    if not repo_root.is_dir():
        raise NotADirectoryError(f"repo_root is not a directory: {repo_root}")
    files = pr_files if pr_files is not None else _enumerate_repo(repo_root)
    findings: list[Finding] = []
    findings.extend(_check_schema_codegen(repo_root, files))
    findings.extend(_check_ci_no_notes(repo_root, files))
    findings.extend(_check_docker_no_notes(repo_root, files))
    findings.sort(key=lambda f: (f.category, f.file, f.line, f.code))
    by_category: dict[str, int] = {}
    for f in findings:
        by_category[f.category] = by_category.get(f.category, 0) + 1
    return {
        "schema_version": SCHEMA_VERSION,
        "timestamp": _local_timestamp(),
        "repo_root": str(repo_root.resolve()),
        "total_findings": len(findings),
        "by_category": dict(sorted(by_category.items())),
        "findings": [asdict(f) for f in findings],
    }


def _parse_argv(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Step 19 — Operational / deployment scanner.",
        prog="operational",
    )
    parser.add_argument("repo_root")
    parser.add_argument("out_dir")
    parser.add_argument("--pr-files-from")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = _parse_argv(argv[1:])
    repo_root = Path(args.repo_root).resolve()
    out_dir = Path(args.out_dir).resolve()
    try:
        out_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"out_dir unwritable: {exc}", file=sys.stderr)
        return 1
    try:
        pr_files = _load_pr_files(repo_root, Path(args.pr_files_from) if args.pr_files_from else None)
        payload = detect(repo_root, pr_files)
    except (FileNotFoundError, NotADirectoryError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    out_path = out_dir / f"{payload['timestamp']}-operational.json"
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
