"""Pipeline-efficacy integration tests (TRDD-7e364ace, all 24 steps).

For every script-backed step in the bug-detection pipeline, this test
plants the EXACT bug patterns the detector is supposed to catch into a
fixture directory, invokes the detector as a subprocess (the same way
the pipeline does), and asserts that every expected finding-code
actually fires.

Quality-gate semantics (per user directive 2026-05-17):
- This test is a hard gate. A single missed code fails the test.
- CI blocks merge on failure; publish.py blocks release on failure.
- No push goes out without zero missed issues.

Steps whose detector is an LLM agent (1, 2, 3, 4, 17, 18, 20, 21, 22,
23) cannot be mechanically exercised from a one-shot harness — those
remain documented in agents/ but are not gated here.

Run locally:
    uv run pytest tests/integration/ -v
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

import pytest

PLUGIN_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPTS = PLUGIN_ROOT / "scripts" / "prereview"


@dataclass(frozen=True)
class StepSpec:
    step: int
    name: str
    script: str
    cli_form: str  # "script" | "module" | "diff"
    files: dict[str, str] = field(default_factory=dict)
    expected_codes: tuple[str, ...] = ()
    extra_args: tuple[str, ...] = ()


# ---------------------------------------------------------------------------
# Fixture seeds — one StepSpec per testable step.
# ---------------------------------------------------------------------------


STEP_0 = StepSpec(
    step=0,
    name="domain-detection",
    script="detect_languages_and_domains.py",
    cli_form="module",
    files={
        "a.py": "print('hi')\n",
        "b.ts": "console.log('hi');\n",
        "tsconfig.json": '{"compilerOptions":{}}\n',
        "c.go": "package main\nfunc main() { println(\"hi\") }\n",
        "go.mod": "module x\n",
        "d.rs": "fn main(){println!(\"hi\");}\n",
        "Cargo.toml": "[package]\nname=\"x\"\nversion=\"0.0.1\"\n",
        "e.swift": "print(\"hi\")\n",
        "Package.swift": "// swift-tools-version:5.5\n",
        "f.ex": "IO.puts(\"hi\")\n",
        "mix.exs": "defmodule X.MixProject do\nend\n",
        "g.sol": "pragma solidity ^0.8.0;\ncontract C { }\n",
        "foundry.toml": "[profile.default]\n",
        "Dockerfile": "FROM python:3.12\n",
        "schema.graphql": "type Query { hello: String }\n",
        "requirements.txt": "requests\n",
        "package.json": '{"name":"x","version":"0.0.1"}\n',
    },
)

STEP_5 = StepSpec(
    step=5,
    name="linter-pre-flight",
    script="run_linters.py",
    cli_form="script",
    files={
        "bad.py": "import os, sys\n\n\ndef f():\n    x=1\n    return x\n",
        "Dockerfile": "FROM ubuntu:latest\nUSER root\nRUN apt-get update\n",
    },
    extra_args=("--tools", "ruff,hadolint"),
)

STEP_6 = StepSpec(
    step=6,
    name="cross-layer-drift",
    script="cross_layer.py",
    cli_form="script",
    files={
        ".env.example": "DOC_ONLY_VAR=x\n",
        "app.py": (
            "import os\n"
            "X = os.environ['CODE_ONLY_VAR']\n"
            "Y = os.getenv('ANOTHER_CODE_ONLY')\n"
        ),
        "gen.py": (
            "# DO NOT EDIT — generated by codegen-tool\n"
            "VALUE = 42\n"
        ),
        "utils.py": (
            "def parse_old(x):\n"
            "    return x\n"
            "\n\n"
            "def helper_deprecated():\n"
            "    return None\n"
        ),
    },
    expected_codes=(
        "USED_IN_CODE_NOT_DOCUMENTED",
        "DOCUMENTED_NOT_USED",
        "GENERATED_BANNER_PRESENT",
        "DEPRECATED_NAME_SUFFIX",
    ),
)

STEP_7 = StepSpec(
    step=7,
    name="multi-tenant",
    script="multi_tenant.py",
    cli_form="script",
    files={
        "queries.py": (
            "def list_user_items(user_id):\n"
            "    return User.objects.filter(user=user_id)\n"
            "\n\n"
            "def get_items(user_id):\n"
            "    return session.query(Item).filter_by(user_id=user_id).all()\n"
        ),
        "cache.ts": (
            "import redis from './r';\n"
            "export function read(userId: string) {\n"
            "  return redis.get(`item:${userId}`);\n"
            "}\n"
        ),
        "state.py": "CACHE: dict = {}\n",
        "prisma.ts": (
            "export async function findOrders(userId: string) {\n"
            "  return prisma.order.findMany({ where: { userId } });\n"
            "}\n"
        ),
    },
    expected_codes=(
        "CACHE_KEY_NO_TENANT",
        "MODULE_STATE",
        "FN_SIG_NO_TENANT",
        "DJANGO_FILTER",
        "SQLALCHEMY_FILTER_BY",
        "PRISMA_WHERE",
    ),
)

STEP_8 = StepSpec(
    step=8,
    name="silent-failure",
    script="silent_failure.py",
    cli_form="script",
    files={
        "py_silent.py": textwrap.dedent(
            """
            import logging
            import os

            log = logging.getLogger(__name__)

            def bare_except():
                try:
                    risky()
                except:
                    pass

            def broad_log_only():
                try:
                    risky()
                except Exception as e:
                    log.error(e)

            def todo_in_handler():
                try:
                    risky()
                except Exception:
                    # TODO(emasoft): handle this
                    return None

            def mock_fallback():
                # MOCK_FALLBACK targets env-based shapes specifically.
                if os.environ.get("ENV") != "prod":
                    return mock_api()
                return real_api()
            """
        ).lstrip(),
        "js_silent.ts": textwrap.dedent(
            """
            async function fetchUser(id: string) {
                try {
                    return await api.fetch(id);
                } catch (e) {
                    console.error(e);
                }
            }

            async function getMaybe(response: Response) {
                return response?.json();
            }
            """
        ).lstrip(),
    },
    expected_codes=(
        "SILENT_BARE",
        "SILENT_EMPTY",
        "SILENT_LOG_ONLY",
        "TODO_IN_HANDLER",
        "MOCK_FALLBACK",
        "OPTIONAL_CHAIN_FALLIBLE",
    ),
)

STEP_9 = StepSpec(
    step=9,
    name="concurrency",
    script="concurrency.py",
    cli_form="script",
    files={
        "async_py.py": textwrap.dedent(
            """
            import asyncio

            async def worker():
                await asyncio.sleep(1)

            async def main():
                asyncio.create_task(worker())
                asyncio.ensure_future(worker())
            """
        ).lstrip(),
        "promises.ts": textwrap.dedent(
            """
            export async function leak() {
                fetch("/api/items");
                Promise.all([fetch("/a"), fetch("/b")]);
            }
            """
        ).lstrip(),
        "concur.go": textwrap.dedent(
            """
            package main

            import "fmt"

            func leak() {
                go fmt.Println("leak")
                fmt.Println("done")
                fmt.Println("done2")
            }

            func bug() {
                ch := make(chan int, 1)
                close(ch)
                ch <- 1
            }
            """
        ).lstrip(),
    },
    expected_codes=(
        "DETACHED_CREATE_TASK",
        "FLOATING_PROMISE",
        "PROMISE_NO_CATCH",
        "GOROUTINE_NO_SYNC",
        "CHANNEL_SEND_AFTER_CLOSE",
    ),
)

STEP_10 = StepSpec(
    step=10,
    name="complexity",
    script="complexity.py",
    cli_form="script",
    files={
        "complex.py": textwrap.dedent(
            """
            import os  # never used

            def too_many_params(a, b, c, d, e, f, g, h):
                return a + b + c + d + e + f + g + h

            def too_long():
            """
        ).lstrip()
        + "\n".join([f"    x = {i}" for i in range(60)])
        + "\n    return x\n\n"
        + textwrap.dedent(
            """
            def too_many_branches(x):
                if x == 1: return 1
                if x == 2: return 2
                if x == 3: return 3
                if x == 4: return 4
                if x == 5: return 5
                if x == 6: return 6
                if x == 7: return 7
                if x == 8: return 8
                return 0

            def unreachable():
                return 1
                print("never")

            def _orphan():
                return 42
            """
        ),
    },
    expected_codes=(
        "FN_TOO_LONG",
        "TOO_MANY_PARAMS",
        "TOO_MANY_BRANCHES",
        "UNUSED_IMPORT",
        "UNREACHABLE",
        "ORPHAN_MODULE_DEF",
    ),
)

STEP_11 = StepSpec(
    step=11,
    name="awc-extensions",
    script="awc_extensions.py",
    cli_form="script",
    files={
        "pyproject.toml": textwrap.dedent(
            """
            [project]
            name = "fixture"
            version = "0.0.1"
            dependencies = ["numpy"]
            """
        ).lstrip(),
        "app.py": textwrap.dedent(
            """
            import requests

            API_URL = "https://api.production-service.io/v1/users"
            BIND_IP = "10.20.30.40"
            CONFIG_PATH = "/etc/myapp/config.yml"
            port = 5432
            DB_PORT = 5432
            RETRY_COUNT = 4242

            def run():
                return requests.get(API_URL).json()
            """
        ).lstrip(),
    },
    expected_codes=(
        "UNDECLARED_DEP",
        "UNUSED_DEP",
        "HARDCODED_URL",
        "HARDCODED_IP",
        "HARDCODED_PATH",
        "HARDCODED_PORT",
        "MAGIC_NUMBER",
    ),
)

STEP_12 = StepSpec(
    step=12,
    name="docstring-diff",
    script="docstring_diff.py",
    cli_form="script",
    files={
        "ghost.py": textwrap.dedent(
            '''
            def add(a, b):
                """Add two numbers.

                :param a: first value
                :param b: second value
                :param ghost: a parameter that does not exist
                """
                return a + b

            def missing(a, b, c):
                """Sum values.

                :param a: first
                :param b: second
                """
                return a + b + c

            def trivial():
                """Does the thing."""
                return 1
            '''
        ).lstrip(),
        "contradiction.py": textwrap.dedent(
            """
            MAX_RETRIES = 10  # default is 5
            TIMEOUT_SECONDS = 300  # was 60 — bump for slow CI
            """
        ).lstrip(),
    },
    expected_codes=(
        "DOCSTRING_PARAM_GHOST",
        "DOCSTRING_PARAM_MISSING",
        "TRIVIAL_DOCSTRING",
        "COMMENT_CONTRADICTS_LITERAL",
    ),
)

STEP_13 = StepSpec(
    step=13,
    name="test-quality",
    script="test_quality.py",
    cli_form="script",
    files={
        "tests/test_x.py": textwrap.dedent(
            """
            from unittest.mock import patch

            def test_no_assertion():
                value = compute(1)

            def test_assert_true_literal():
                assert True

            @patch("mymodule.target_function")
            def test_mock_sut(mock_target):
                mock_target.return_value = 1
                from mymodule import target_function
                assert target_function() == 1
            """
        ).lstrip(),
        "tests/foo.test.ts": textwrap.dedent(
            """
            describe("x", () => {
              it("trivial true", () => {
                expect(true).toBe(true);
              });
              it("truthy", () => {
                expect(1).toBeTruthy();
              });
              it("no assertion", () => {
                const x = 1;
              });
            });
            """
        ).lstrip(),
    },
    expected_codes=(
        "NO_ASSERTION_TEST",
        "ASSERT_TRUE_LITERAL",
        "MOCK_REPLACES_SUT_HEURISTIC",
        "JS_EXPECT_TRUE",
        "JS_EXPECT_TRUTHY",
        "JS_NO_ASSERTION",
    ),
)

STEP_14 = StepSpec(
    step=14,
    name="performance",
    script="performance.py",
    cli_form="script",
    files={
        "queries.py": textwrap.dedent(
            """
            def get_orders(users):
                out = []
                for u in users:
                    out.append(db.query(Order).filter(Order.user_id == u.id).all())
                return out

            def fib(n):
                if n < 2:
                    return n
                return fib(n-1) + fib(n-2)

            def read_huge():
                with open("/var/log/huge.log", "r") as f:
                    return f.read()
            """
        ).lstrip(),
        "loop.js": textwrap.dedent(
            """
            for (const u of users) {
                db.query("SELECT * FROM orders WHERE user_id = ?", [u.id]);
            }
            const data = fs.readFileSync("/tmp/big.log");
            """
        ).lstrip(),
        "loop.go": textwrap.dedent(
            """
            package main

            func leak(users []User) {
                for _, u := range users {
                    db.Query("SELECT * FROM orders WHERE user_id = ?", u.ID)
                }
            }
            """
        ).lstrip(),
    },
    expected_codes=(
        "N_PLUS_ONE_LOOP",
        "RECURSIVE_NO_MEMO",
        "LARGE_FILE_FULL_READ",
        "JS_N_PLUS_ONE_LOOP",
        "JS_LARGE_FILE_SYNC_READ",
        "GO_DB_IN_LOOP",
    ),
)

STEP_15 = StepSpec(
    step=15,
    name="database",
    script="database.py",
    cli_form="script",
    files={
        "migrations/001_add_users.py": textwrap.dedent(
            """
            def upgrade():
                op.create_table('users')

            def downgrade():
                pass
            """
        ).lstrip(),
        "migrations/002_drop_old.py": textwrap.dedent(
            """
            def upgrade():
                op.drop_table('old')
            """
        ).lstrip(),
        "queries.py": textwrap.dedent(
            """
            def find_user(cur, user_id):
                cur.execute(f"SELECT * FROM users WHERE id = {user_id}")
                return cur.fetchone()
            """
        ).lstrip(),
        "schema_ops.sql": (
            "ALTER TABLE users ADD COLUMN x INT;\n"
            "DROP TABLE archived_users;\n"
        ),
    },
    expected_codes=(
        "EMPTY_DOWNGRADE",
        "MISSING_DOWNGRADE",
        "SQL_INJECTION_FSTRING",
        "ALTER_TABLE_OUTSIDE_MIGRATION",
        "DROP_TABLE_OUTSIDE_MIGRATION",
    ),
)

STEP_16 = StepSpec(
    step=16,
    name="type-design-gate",
    script="find_new_public_types.py",
    cli_form="diff",
    files={
        "fake.diff": textwrap.dedent(
            """
            diff --git a/types.py b/types.py
            index 1111111..2222222 100644
            --- a/types.py
            +++ b/types.py
            @@ -1,1 +1,12 @@
             # types
            +class NewPublic:
            +    def __init__(self, x: int) -> None:
            +        self.x = x
            +
            +@dataclass
            +class Another:
            +    y: int
            +
            +def _private():
            +    return 1
            """
        ).lstrip(),
    },
)

STEP_19 = StepSpec(
    step=19,
    name="operational",
    script="operational.py",
    cli_form="script",
    files={
        "api.proto": "syntax = \"proto3\";\nmessage User { string id = 1; }\n",
        ".github/workflows/ci.yml": (
            "name: CI\non: [push]\njobs:\n  test:\n"
            "    runs-on: ubuntu-latest\n    steps:\n      - run: echo hi\n"
        ),
        "Dockerfile": "FROM python:3.12\nRUN pip install -e .\n",
    },
    expected_codes=(
        "SCHEMA_NO_CODEGEN",
        "CI_NO_NOTES",
        "DOCKERFILE_NO_NOTES",
    ),
)


ALL_SPECS = [
    STEP_0, STEP_5, STEP_6, STEP_7, STEP_8, STEP_9, STEP_10,
    STEP_11, STEP_12, STEP_13, STEP_14, STEP_15, STEP_16, STEP_19,
]


# ---------------------------------------------------------------------------
# Harness helpers
# ---------------------------------------------------------------------------


def _write_fixture(fixture_dir: Path, files: dict[str, str]) -> None:
    for relpath, content in files.items():
        f = fixture_dir / relpath
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(content, encoding="utf-8")


def _run_detector(spec: StepSpec, fixture_dir: Path, out_dir: Path) -> subprocess.CompletedProcess:
    if spec.cli_form == "module":
        cmd = [
            sys.executable, "-m",
            "scripts.prereview." + spec.script.removesuffix(".py"),
            str(fixture_dir), str(out_dir),
        ]
    elif spec.cli_form == "diff":
        diff_path = fixture_dir / "fake.diff"
        cmd = [sys.executable, str(SCRIPTS / spec.script), str(diff_path), str(out_dir)]
    else:
        cmd = [
            sys.executable, str(SCRIPTS / spec.script),
            str(fixture_dir), str(out_dir), *spec.extra_args,
        ]
    return subprocess.run(
        cmd, capture_output=True, text=True,
        cwd=str(PLUGIN_ROOT), timeout=300,
    )


def _load_report(out_dir: Path) -> dict:
    json_files = sorted(out_dir.glob("*.json"))
    assert json_files, f"detector wrote no JSON in {out_dir}"
    return json.loads(json_files[0].read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def _spec_id(spec: StepSpec) -> str:
    return f"step-{spec.step:02d}-{spec.name}"


@pytest.mark.parametrize("spec", ALL_SPECS, ids=_spec_id)
def test_pipeline_step_detects_seeded_bugs(spec: StepSpec, tmp_path: Path) -> None:
    """Each step must catch every bug code it claims to catch.

    Fixture: seeded under ``tmp_path`` (outside the plugin's git repo, so
    ``git ls-files`` enumeration sees every file we plant).

    Gate: any expected code missing from the JSON output fails the test.
    """
    fixture_dir = tmp_path / "fixture"
    out_dir = tmp_path / "out"
    fixture_dir.mkdir()
    out_dir.mkdir()
    _write_fixture(fixture_dir, spec.files)

    proc = _run_detector(spec, fixture_dir, out_dir)
    assert proc.returncode == 0, (
        f"detector exited {proc.returncode}\n"
        f"stderr: {proc.stderr[-500:]}"
    )

    report = _load_report(out_dir)

    if spec.step == 0:
        # Domain detection — verify every seeded language/domain is detected.
        langs = report.get("languages", {})
        domains = report.get("domains", {})
        expected_langs = {"python", "typescript", "go", "rust",
                          "swift", "elixir", "solidity"}
        expected_domains = {"docker", "graphql"}
        missed_langs = {ln for ln in expected_langs
                        if not langs.get(ln, {}).get("detected")}
        missed_doms = {dn for dn in expected_domains
                       if not domains.get(dn, {}).get("detected")}
        assert not missed_langs and not missed_doms, (
            f"Step 0 missed languages={sorted(missed_langs)} "
            f"domains={sorted(missed_doms)}"
        )
        return

    if spec.step == 16:
        # Type-design gate — must surface NewPublic and Another, not _private.
        found = {t.get("name") for t in report.get("types", [])}
        assert "NewPublic" in found, f"gate missed NewPublic; got {sorted(found)}"
        assert "Another" in found, f"gate missed Another; got {sorted(found)}"
        assert "_private" not in found, (
            f"gate leaked private symbol _private; got {sorted(found)}"
        )
        return

    if spec.step == 5:
        # Linter pre-flight — at least one external tool must run.
        # If `ruff` isn't on PATH, skip rather than fail (host-dependent).
        tools_run = report.get("tools_run") or []
        if not tools_run:
            pytest.skip(
                "No external linters installed on PATH; "
                "step 5 efficacy depends on the host environment."
            )
        # If ruff ran, it must have produced findings on the seeded `bad.py`.
        by_tool = report.get("by_tool_count", {})
        if "ruff" in tools_run:
            assert by_tool.get("ruff", 0) > 0, (
                "ruff ran but found nothing on the seeded bad.py — "
                "either the fixture is stale or ruff config is off"
            )
        return

    # General case — every expected code must fire ≥1 time.
    findings = report.get("findings", [])
    found_codes = {f.get("code") for f in findings}
    expected = set(spec.expected_codes)
    missing = expected - found_codes
    assert not missing, (
        f"Step {spec.step} ({spec.name}) detector missed "
        f"{len(missing)} expected code(s): {sorted(missing)}\n"
        f"  Codes found: {sorted(found_codes)}\n"
        f"  Total findings: {len(findings)}\n"
        f"  Fixture dir: {fixture_dir}\n"
        f"  This is a QUALITY-GATE failure — the detector regressed."
    )


def test_all_24_steps_accounted_for() -> None:
    """Sanity check: every step number is either mechanically tested here
    or documented as agent-only.

    Steps 0-23 = 24 total. This test fails if a new step gets added to
    the TRDD without updating either ALL_SPECS or AGENT_ONLY.
    """
    mechanical = {s.step for s in ALL_SPECS}
    agent_only = {1, 2, 3, 4, 17, 18, 20, 21, 22, 23}
    covered = mechanical | agent_only
    expected = set(range(24))
    missing = expected - covered
    assert not missing, (
        f"Step(s) {sorted(missing)} are not accounted for in either "
        f"the mechanical-test specs or the agent-only allow-list. "
        f"If you added a step to TRDD-7e364ace, update this test."
    )
