"""Unit tests for Step 19 — operational scanner."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.prereview import operational as op


def _write(p: Path, content: str = "") -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def _list_file(p: Path, items: list[str]) -> Path:
    _write(p, "\n".join(items) + "\n")
    return p


# ---- schema / codegen drift -----------------------------------------------


def test_proto_change_without_generated_flagged(tmp_path: Path) -> None:
    _write(tmp_path / "api" / "users.proto", "message User { string id = 1; }\n")
    _write(tmp_path / "api" / "other.py", "x = 1\n")  # not @generated
    listing = _list_file(tmp_path / "pr.txt", ["api/users.proto", "api/other.py"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "SCHEMA_NO_CODEGEN" in codes


def test_proto_change_with_generated_not_flagged(tmp_path: Path) -> None:
    _write(tmp_path / "api" / "users.proto", "message User { string id = 1; }\n")
    _write(
        tmp_path / "api" / "users_pb2.py",
        "# @generated by protoc-gen-python\n# DO NOT EDIT\n",
    )
    listing = _list_file(tmp_path / "pr.txt", ["api/users.proto", "api/users_pb2.py"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "SCHEMA_NO_CODEGEN" not in codes


def test_graphql_change_without_generated_flagged(tmp_path: Path) -> None:
    _write(tmp_path / "schema.graphql", "type Query { me: User }\n")
    _write(tmp_path / "src" / "app.ts", "export const x = 1;\n")
    listing = _list_file(tmp_path / "pr.txt", ["schema.graphql", "src/app.ts"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "SCHEMA_NO_CODEGEN" in codes


def test_openapi_change_with_generated_client_not_flagged(tmp_path: Path) -> None:
    _write(tmp_path / "api" / "openapi.yaml", "openapi: 3.0.0\n")
    _write(
        tmp_path / "api" / "client.gen.ts",
        "// @generated by openapi-generator-cli\nexport const api = {};\n",
    )
    listing = _list_file(tmp_path / "pr.txt", ["api/openapi.yaml", "api/client.gen.ts"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "SCHEMA_NO_CODEGEN" not in codes


def test_openapi_change_without_generated_flagged(tmp_path: Path) -> None:
    """The canonical bare `openapi.yaml` (no dot before "openapi") must be
    recognized as a schema source and flag SCHEMA_NO_CODEGEN when no generated
    client accompanies it. Regression: only the dotted `.openapi.yaml` matched,
    so `api/openapi.yaml` was invisible and the negative test passed vacuously.
    """
    _write(tmp_path / "api" / "openapi.yaml", "openapi: 3.0.0\n")
    _write(tmp_path / "src" / "app.ts", "export const x = 1;\n")
    listing = _list_file(tmp_path / "pr.txt", ["api/openapi.yaml", "src/app.ts"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "SCHEMA_NO_CODEGEN" in codes


# ---- CI without notes -----------------------------------------------------


def test_workflow_change_without_docs_flagged(tmp_path: Path) -> None:
    _write(tmp_path / ".github" / "workflows" / "ci.yml", "name: CI\non: push\n")
    _write(tmp_path / "src" / "main.py", "x = 1\n")
    listing = _list_file(tmp_path / "pr.txt", [".github/workflows/ci.yml", "src/main.py"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "CI_NO_NOTES" in codes


def test_workflow_change_with_readme_update_not_flagged(tmp_path: Path) -> None:
    _write(tmp_path / ".github" / "workflows" / "ci.yml", "name: CI\non: push\n")
    _write(tmp_path / "README.md", "# Updated\n")
    listing = _list_file(tmp_path / "pr.txt", [".github/workflows/ci.yml", "README.md"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "CI_NO_NOTES" not in codes


def test_gitlab_ci_treated_same_way(tmp_path: Path) -> None:
    _write(tmp_path / ".gitlab-ci.yml", "stages: [test]\n")
    _write(tmp_path / "src" / "main.py", "x = 1\n")
    listing = _list_file(tmp_path / "pr.txt", [".gitlab-ci.yml", "src/main.py"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "CI_NO_NOTES" in codes


# ---- Dockerfile without notes ---------------------------------------------


def test_dockerfile_change_without_docs_flagged(tmp_path: Path) -> None:
    _write(tmp_path / "Dockerfile", "FROM python:3.12-slim\n")
    _write(tmp_path / "src" / "main.py", "x = 1\n")
    listing = _list_file(tmp_path / "pr.txt", ["Dockerfile", "src/main.py"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "DOCKERFILE_NO_NOTES" in codes


def test_dockerfile_with_readme_update_not_flagged(tmp_path: Path) -> None:
    _write(tmp_path / "Dockerfile", "FROM python:3.12-slim\n")
    _write(tmp_path / "README.md", "# Updated container base\n")
    listing = _list_file(tmp_path / "pr.txt", ["Dockerfile", "README.md"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "DOCKERFILE_NO_NOTES" not in codes


def test_docker_compose_treated_same_way(tmp_path: Path) -> None:
    _write(tmp_path / "docker-compose.yml", "services:\n  app:\n    image: x\n")
    _write(tmp_path / "src" / "main.py", "x = 1\n")
    listing = _list_file(tmp_path / "pr.txt", ["docker-compose.yml", "src/main.py"])
    result = op.detect(tmp_path, pr_files=op._load_pr_files(tmp_path, listing))
    codes = {f["code"] for f in result["findings"]}
    assert "DOCKERFILE_NO_NOTES" in codes


# ---- determinism + CLI ----------------------------------------------------


def test_findings_deterministically_sorted(tmp_path: Path) -> None:
    _write(tmp_path / "api" / "a.proto", "message A {}\n")
    _write(tmp_path / "api" / "b.proto", "message B {}\n")
    listing = _list_file(tmp_path / "pr.txt", ["api/a.proto", "api/b.proto"])
    pr_files = op._load_pr_files(tmp_path, listing)
    r1 = op.detect(tmp_path, pr_files)
    r2 = op.detect(tmp_path, pr_files)
    r1.pop("timestamp")
    r2.pop("timestamp")
    assert json.dumps(r1, sort_keys=True) == json.dumps(r2, sort_keys=True)


def test_main_emits_file(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    out = tmp_path / "out"
    _write(repo / "Dockerfile", "FROM python:3.12-slim\n")
    _write(repo / "src" / "main.py", "x = 1\n")
    listing = repo / "pr.txt"
    listing.write_text("Dockerfile\nsrc/main.py\n", encoding="utf-8")
    rc = op.main(["operational", str(repo), str(out), "--pr-files-from", str(listing)])
    assert rc == 0
    body = json.loads(next(out.iterdir()).read_text(encoding="utf-8"))
    assert body["schema_version"] == 1
