"""Unit tests for Step 6 — cross-layer drift detector."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.prereview import cross_layer as cl


def _write(p: Path, content: str = "") -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


# ---- env-var drift ---------------------------------------------------------


def test_env_var_referenced_in_code_but_not_documented(tmp_path: Path) -> None:
    _write(tmp_path / ".env.example", "DATABASE_URL=postgres://localhost/db\n")
    _write(
        tmp_path / "app.py",
        "import os\nDB = os.environ.get('DATABASE_URL')\nSECRET = os.getenv('UNDOCUMENTED_SECRET')\n",
    )
    result = cl.detect(tmp_path)
    drift = [f for f in result["findings"] if f["category"] == "env_var_drift"]
    used_not_doc = [f for f in drift if f["code"] == "USED_IN_CODE_NOT_DOCUMENTED"]
    assert len(used_not_doc) == 1
    assert "UNDOCUMENTED_SECRET" in used_not_doc[0]["message"]


def test_env_var_documented_but_unused(tmp_path: Path) -> None:
    _write(
        tmp_path / ".env.example",
        "DATABASE_URL=postgres://localhost/db\nORPHAN_KEY=foo\n",
    )
    _write(tmp_path / "app.py", "import os\nDB = os.environ.get('DATABASE_URL')\n")
    result = cl.detect(tmp_path)
    drift = [f for f in result["findings"] if f["category"] == "env_var_drift"]
    docs_unused = [f for f in drift if f["code"] == "DOCUMENTED_NOT_USED"]
    assert len(docs_unused) == 1
    assert "ORPHAN_KEY" in docs_unused[0]["message"]


def test_compose_environment_block_counts_as_declaration(tmp_path: Path) -> None:
    _write(
        tmp_path / "docker-compose.yml",
        "services:\n"
        "  app:\n"
        "    image: x\n"
        "    environment:\n"
        "      - PORT=3000\n"
        "      - DATABASE_URL=postgres://x/y\n"
        "    ports: ['3000:3000']\n",
    )
    _write(tmp_path / "app.py", "import os\nP = os.environ.get('PORT')\n")
    result = cl.detect(tmp_path)
    drift = [f for f in result["findings"] if f["category"] == "env_var_drift"]
    # PORT and DATABASE_URL are both declared. PORT is used; DATABASE_URL is not.
    docs_unused = [f for f in drift if f["code"] == "DOCUMENTED_NOT_USED"]
    assert any("DATABASE_URL" in f["message"] for f in docs_unused)
    used_not_doc = [f for f in drift if f["code"] == "USED_IN_CODE_NOT_DOCUMENTED"]
    assert not used_not_doc  # PORT is documented


def test_short_lowercase_vars_are_filtered(tmp_path: Path) -> None:
    """Bash patterns can match `$X` / `$lowercase`; the filter excludes those."""
    _write(
        tmp_path / "script.sh",
        "#!/bin/bash\necho $X\necho ${db_path}\necho ${MY_REAL_VAR}\n",
    )
    result = cl.detect(tmp_path)
    drift = [f for f in result["findings"] if f["category"] == "env_var_drift"]
    # Only MY_REAL_VAR should be flagged.
    used_not_doc = [f for f in drift if f["code"] == "USED_IN_CODE_NOT_DOCUMENTED"]
    assert len(used_not_doc) == 1
    assert "MY_REAL_VAR" in used_not_doc[0]["message"]


# ---- generated-file detection ----------------------------------------------


def test_generated_marker_at_top_of_file(tmp_path: Path) -> None:
    _write(
        tmp_path / "client.gen.ts",
        "// @generated\n// Code generated by openapi-generator-cli\nexport const api = { foo: () => null };\n",
    )
    _write(tmp_path / "main.ts", "// hand-written\nconst x = 1;\n")
    result = cl.detect(tmp_path)
    gen = [f for f in result["findings"] if f["category"] == "generated_drift"]
    assert len(gen) == 1
    assert "client.gen.ts" in gen[0]["file"]


def test_generated_marker_only_in_first_50_lines(tmp_path: Path) -> None:
    """A `@generated` mention buried deep in the file isn't treated as a banner."""
    long_body = ["// line " + str(i) for i in range(200)]
    long_body[100] = "// @generated"
    _write(tmp_path / "deep.ts", "\n".join(long_body))
    result = cl.detect(tmp_path)
    gen = [f for f in result["findings"] if f["category"] == "generated_drift"]
    assert not gen


# ---- orphan naming ---------------------------------------------------------


def test_orphan_naming_suffixes_detected(tmp_path: Path) -> None:
    _write(
        tmp_path / "app.py",
        "def fetch_user_v1(): pass\n"
        "def fetch_user_v2(): pass\n"
        "old_handler = fetch_user_v1\n"
        "def regular_function(): pass\n",
    )
    result = cl.detect(tmp_path)
    orphans = [f for f in result["findings"] if f["category"] == "orphan_naming"]
    # fetch_user_v1 appears 2x (def + usage). fetch_user_v2 appears 1x.
    # regular_function should NOT appear.
    names = {f["message"].split("'")[1] for f in orphans}
    assert "fetch_user_v1" in names
    assert "fetch_user_v2" in names
    assert "regular_function" not in names


def test_orphan_naming_does_not_match_short_words(tmp_path: Path) -> None:
    _write(tmp_path / "app.py", "x = 1\ny = 'old'\n")  # 'old' is a STRING, not a symbol
    result = cl.detect(tmp_path)
    orphans = [f for f in result["findings"] if f["category"] == "orphan_naming"]
    assert not orphans


# ---- driver / determinism --------------------------------------------------


def test_findings_are_sorted_deterministically(tmp_path: Path) -> None:
    _write(tmp_path / "a.py", "import os\nA = os.environ.get('A_VAR')\n")
    _write(tmp_path / "b.py", "import os\nB = os.environ.get('B_VAR')\n")
    r1 = cl.detect(tmp_path)
    r2 = cl.detect(tmp_path)
    r1.pop("timestamp")
    r2.pop("timestamp")
    assert json.dumps(r1, sort_keys=True) == json.dumps(r2, sort_keys=True)


def test_main_emits_file(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    out = tmp_path / "out"
    _write(repo / "app.py", "import os\nx = os.environ.get('FOO_VAR')\n")
    rc = cl.main(["cross_layer", str(repo), str(out)])
    assert rc == 0
    files = list(out.iterdir())
    assert len(files) == 1
    body = json.loads(files[0].read_text(encoding="utf-8"))
    assert body["schema_version"] == 1
    assert "findings" in body


def test_main_rejects_bad_repo_root(tmp_path: Path, capsys) -> None:
    rc = cl.main(["cross_layer", str(tmp_path / "missing"), str(tmp_path / "out")])
    assert rc == 1
    err = capsys.readouterr().err
    assert "directory" in err.lower()


def test_pr_mode_keeps_used_not_documented_but_suppresses_documented_not_used(tmp_path: Path) -> None:
    """In PR mode, references come from the PR subset while declarations stay
    repo-wide, so USED_IN_CODE_NOT_DOCUMENTED still fires (the PR references an
    undeclared var). DOCUMENTED_NOT_USED must NOT fire in PR mode.

    Regression (MAJ-10): the old behaviour flagged DATABASE_URL as
    DOCUMENTED_NOT_USED even though old_file.py references it — it IS used, just
    not by the PR. The verifier confirmed this as a false-positive bomb; the
    earlier "intentional" rationale only held for the opposite direction.
    """
    _write(tmp_path / ".env.example", "DATABASE_URL=x\nPR_NEW_VAR=y\n")
    _write(tmp_path / "old_file.py", "import os\nDB = os.environ.get('DATABASE_URL')\n")
    _write(tmp_path / "pr_changed.py", "import os\nUNDOC = os.environ.get('UNDOCUMENTED_VAR')\n")
    list_file = tmp_path / "pr-files.txt"
    list_file.write_text("pr_changed.py\n", encoding="utf-8")
    rc = cl.main(["cross_layer", str(tmp_path), str(tmp_path / "out"), "--pr-files-from", str(list_file)])
    assert rc == 0
    files = list((tmp_path / "out").iterdir())
    body = json.loads(files[0].read_text(encoding="utf-8"))
    drift = [f for f in body["findings"] if f["category"] == "env_var_drift"]
    used_not_doc = [f["message"] for f in drift if f["code"] == "USED_IN_CODE_NOT_DOCUMENTED"]
    assert any("UNDOCUMENTED_VAR" in m for m in used_not_doc)
    # DATABASE_URL is declared AND used (old_file.py, outside the PR subset), so
    # it must NOT be flagged DOCUMENTED_NOT_USED — the MAJ-10 false positive.
    docs_unused = [f for f in drift if f["code"] == "DOCUMENTED_NOT_USED"]
    assert docs_unused == []
